sudo: false
language: go
go:
  - 1.5
  - 1.6
  - 1.7beta2
install:
  - go get
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update
script:
  - gometalinter ./... --deadline=30s
